### ISSUE TITLE
etherscan api key not used

### ISSUE THREAD

**Issue by leitmedium** [acebusters/geth-healthcheck#4]
Hey,

thanks for this module. While reviewing the code I noticed that there seems to be no usage of the etherscan api key. So it won't be used at all, is that right? I assume it still works, because etherscan is kind of lazy about api key usage, though.

Best,

Caspar.

**Comment by troggy** [comment]
Hey Caspar. The latest master is using Infura nodes instead of Etherscan, that's why there is no API key usage. Need to update README 😅

If you want to test against Ethserscan, you can use the previous version: https://github.com/leapdao/eth-node-healthcheck/tree/v1.0.2 (published on npm just now)

**Comment by troggy** [comment]
I've updated README to conform with latest code (published as 1.1.0). Hope it helps

**Comment by leitmedium** [comment]
Hey troggy,

thanks for the quick reply. All good then!
